norkator/paketin-seuranta

app/src/main/java/com/nitramite/courier/CainiaoStrategy.java
What have I done:
* Now it does a GET request to the Cainiao Tracking website and extracts JSON data from HTML
* If Cainiao can't find any information (and origin country is specified in the JSON), it will go into fallback mode, and fetch from that origin country
* When details are fetched, it starts parsing the data
Signed-off-by: Developer From Jokela <developerfromjokela@gmail.com>
=> Fixed Cainiao's Strategy

app/src/main/java/com/nitramite/courier/FourPXStrategy.java, app/src/main/java/com/nitramite/courier/ParcelObject.java, app/src/main/java/com/nitramite/courier/PostNordStrategy.java, app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java, app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java
This class was a big mess. Still partially is but better now:
* Given phase is now actually phase like IN_TRANSPORT / DELIVERED / READY_FOR_PICKUP and not anymore some last event strings
* Turned DELIVERED and READY_FOR_PICKUP other way around so that delivered would be checked first. This fixes few trouble cases.
* Biggest change is that those custom strings are now only lastEventStr which are checked. Makes this process clearer.
=> Refactored phase number class

app/src/main/java/com/nitramite/courier/YanwenStrategy.java
This PR fixes Yanwen tracking and simplifies code with better structure
=> Yanwen fixing

app/src/main/java/com/nitramite/paketinseuranta/Archive.java, app/src/main/java/com/nitramite/paketinseuranta/BackupManager.java, app/src/main/java/com/nitramite/paketinseuranta/BarcodeList.java, app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java, app/src/main/java/com/nitramite/paketinseuranta/Parcel.java, app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java, app/src/main/java/com/nitramite/utils/LocaleUtils.java
=> Fix manual locale/language set problem, SDK29  / Q+

app/src/main/java/com/nitramite/courier/ParcelObject.java, app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java, app/src/main/java/com/nitramite/paketinseuranta/FragmentNumberList.java, app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java, app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java, app/src/main/java/com/nitramite/paketinseuranta/ParcelItem.java, app/src/main/java/com/nitramite/paketinseuranta/updater/UpdaterLogic.java, app/src/main/java/com/nitramite/utils/CarrierUtils.java, app/src/main/java/com/nitramite/utils/LocaleUtils.java
Opening draft PR to connect issues so that nobody else tries to start fixing these yet.
=> Fixing empty insert problem

Jenkinsfile, app/build.gradle, app/src/androidTest/java/com/nitramite/paketinseuranta/ExampleInstrumentedTest.java, app/src/test/java/android/util/Log.java, app/src/test/java/com/nitramite/paketinseuranta/UtilsUnitTest.java
Long time ago there was similar set of espresso and junit  test runners but older versions. There was no tests as there is not now except one sample. Anyway this brings possibility to write them. I may write later within this same PR some.
=> Adding tests run possibilities

README.md
Someone should provide change ideas if there's any.
=> Switching to Semver versioning

app/build.gradle, app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
Only place this worked was after setting adapter -> trackItemsList.setAdapter(mAdapter);
=> Fix issue with pull down swipe refresh list view scroll

app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java
Added if (position == 0) since this was triggered every time swipe was ending for list view, activating swipe layout again.
=> Fix onSwipeEnded method

app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java, app/src/main/res/layout/activity_main_menu.xml, app/src/main/res/layout/content_main_menu.xml
Fix was to put ListView inside SwipeRefresh, had to also change layouts a bit because after change application bar was top of list view.
=> Fix swipe refresh with list view

app/build.gradle
* Tested with Emulator, I see no problems. Views look good too.
=> Set min sdk to 21 (First Lollipop)

app/src/main/java/com/nitramite/adapters/CustomParcelsAdapterV2.java, app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java, app/src/main/java/com/nitramite/paketinseuranta/Parcel.java, app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java
=> Improved phase handling

app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
Problem was on Android new storage permissions
=> Fix parcel image taking feature

app/src/main/java/com/nitramite/courier/YanwenStrategy.java
=> Fix yanwen tracking

app/src/main/java/com/nitramite/paketinseuranta/Archive.java, app/src/main/java/com/nitramite/utils/CSVExporter.java, app/src/main/res/layout/csv_export_layout.xml, app/src/main/res/values-fi-rFI/strings.xml, app/src/main/res/values/strings.xml
So after this, file will be on app own directory at internal storage when using >= Android 10
=> Fix csv export

app/src/main/java/com/nitramite/courier/DHLExpressStrategy.java
This problem was related to TRANSIT phase being transformed to IN_TRANSPORT, which was different after every update time. Just will turn TRANSIT into IN_TRANSPORT so it works like it should.
=> Fix notification issue

app/src/main/java/com/nitramite/paketinseuranta/Archive.java, app/src/main/res/values-fi-rFI/strings.xml, app/src/main/res/values/strings.xml
=> Fix csv export description

app/src/main/java/com/nitramite/courier/UPSStrategy.java, app/src/main/java/com/nitramite/courier/ups/UpsTokenPair.java
=> Fix UPS tracking token issue

.gitignore, Jenkinsfile, app/build.gradle
Opt in process is done at GPDC.
**"AAB Test" stage needs to be cleaned out before merging when this works**
=> Cleaned away after initial testing.
In some point need to test uploading aab to store.
=> Android app bundle

app/src/main/java/com/nitramite/courier/ArraPakettiStrategy.java, app/src/main/java/com/nitramite/courier/CainiaoStrategy.java, app/src/main/java/com/nitramite/courier/DHLActiveTrackingStrategy.java, app/src/main/java/com/nitramite/courier/DHLAmazonStrategy.java, app/src/main/java/com/nitramite/courier/DpdStrategy.java, app/src/main/java/com/nitramite/courier/FedExStrategy.java, app/src/main/java/com/nitramite/courier/FourPXStrategy.java, app/src/main/java/com/nitramite/courier/GlsStrategy.java, app/src/main/java/com/nitramite/courier/MatkahuoltoStrategy.java, app/src/main/java/com/nitramite/courier/PostNordStrategy.java, app/src/main/java/com/nitramite/courier/UPSStrategy.java, app/src/main/java/com/nitramite/courier/USPSStrategy.java, app/src/main/java/com/nitramite/courier/YanwenStrategy.java
Was meant to do something big here but only cleaned some phases. Had some idea for a possible bug but didn't find anything.
=> Phase cleaning

app/src/main/res/values-fi-rFI/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Also corrected restart part because no longer needed.
=> Fix hard coded screen orientation translation

app/src/main/java/com/nitramite/courier/PostNordStrategy.java
=> Postnord new v2 api

Jenkinsfile, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/nitramite/paketinseuranta/BackupManager.java, app/src/main/java/com/nitramite/paketinseuranta/Constants.java, app/src/main/java/com/nitramite/paketinseuranta/MainMenu.java, app/src/main/java/com/nitramite/paketinseuranta/Parcel.java, app/src/main/java/com/nitramite/utils/BackupUtils.java, app/src/main/res/layout/activity_backup_manager.xml, app/src/main/res/values-fi-rFI/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/provider_paths.xml, build.gradle
Fixes some issues and adds feature like exporting db backup.
=> Changes, fixes, updates

app/build.gradle
=> Reorder, upgrade dependencies

Jenkinsfile, app/build.gradle, app/src/main/java/com/nitramite/courier/PostiStrategy.java, app/src/main/java/com/nitramite/utils/TestsUtils.java, app/src/test/java/com/nitramite/paketinseuranta/PostiStrategyTest.java, app/src/test/java/com/nitramite/paketinseuranta/StrategyTest.java
**Idea / Goal**
1. Pull working tracking number from AfterShip with css query using already existing Jsoup.
2. Write tests into one strategy test class.
3. Run tests with Jenkins with each commit.
This way we stay on top when courier changes api etc.
**I only add few for testing to see how long afterShip gives responses before blocking IP or something like that**
=> Developing tests for strategies (junit)

app/src/main/java/com/nitramite/adapters/CustomAutoCompleteAdapter.java, app/src/main/java/com/nitramite/courier/ArraPakettiStrategy.java, app/src/main/java/com/nitramite/courier/BringStrategy.java, app/src/main/java/com/nitramite/courier/CainiaoStrategy.java, app/src/main/java/com/nitramite/courier/ChinaPostAirMailStrategy.java, app/src/main/java/com/nitramite/courier/Courier.java, app/src/main/java/com/nitramite/courier/DHLActiveTrackingStrategy.java, app/src/main/java/com/nitramite/courier/DHLAmazonStrategy.java, app/src/main/java/com/nitramite/courier/DpdStrategy.java, app/src/main/java/com/nitramite/courier/FedExStrategy.java, app/src/main/java/com/nitramite/courier/FourPXStrategy.java, app/src/main/java/com/nitramite/courier/GlsStrategy.java, app/src/main/java/com/nitramite/courier/PostiStrategy.java, app/src/main/java/com/nitramite/courier/USPSStrategy.java, app/src/main/java/com/nitramite/courier/YanwenStrategy.java, app/src/main/java/com/nitramite/paketinseuranta/CarrierDetectorTask.java, app/src/main/java/com/nitramite/paketinseuranta/CustomZoomLayout.java, app/src/main/java/com/nitramite/paketinseuranta/DatabaseHelper.java, app/src/main/java/com/nitramite/paketinseuranta/FragmentNumberList.java, app/src/main/java/com/nitramite/paketinseuranta/FragmentTrackedDelivery.java, app/src/main/java/com/nitramite/paketinseuranta/MyPreferencesActivity.java, app/src/main/java/com/nitramite/paketinseuranta/ParcelEditor.java, app/src/main/java/com/nitramite/paketinseuranta/ParcelService.java, app/src/main/java/com/nitramite/paketinseuranta/Widget.java, app/src/main/java/com/nitramite/utils/CSVExporter.java, app/src/main/java/com/nitramite/utils/Utils.java, app/src/test/java/com/nitramite/paketinseuranta/StrategyTest.java
Did some cleanups, more tests, found problems thanks to tests
=> Random cleanups

app/src/main/java/com/nitramite/adapters/RecyclerItemTouchHelper.java
=> Change swipe sensitivity

app/src/main/java/com/nitramite/paketinseuranta/Archive.java, app/src/main/java/com/nitramite/utils/CSVExporter.java
Just like in backup manager with backups.
This needs bit more testing.
=> Export csv file via intent after saving

app/src/main/java/com/nitramite/courier/PostNordStrategy.java
Did required changes after investigating what has changed.
=> Postnord tracking fix

app/build.gradle, app/src/main/java/com/nitramite/paketinseuranta/BarcodeList.java
=> Barcode list filter away duplicate codes

app/src/main/java/com/nitramite/courier/DHLExpressStrategy.java, app/src/main/java/com/nitramite/paketinseuranta/CarrierDetectorTask.java
Ditched ideas of hacking public tracking interface and used unified api instead with requested api key. Its very simple tracking with stupid rate limit but what ever.
=> DHL Express tracking doesn't work

app/src/main/AndroidManifest.xml, app/src/main/java/com/nitramite/paketinseuranta/Archive.java, app/src/main/java/com/nitramite/paketinseuranta/BackupManager.java, app/src/main/java/com/nitramite/paketinseuranta/Parcel.java
This pull request aims to fix current messy storage writing issues and permission mess. It's possible that write and read external storage permission can be completely removed.
=> Permissions and storage issues
